### ISSUE TITLE
Provide more info on plugin behavior

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/DIPs#10]
This idea has come up a few times in discord. Should we consider ways to expose more information about a given plugin so users can decide if they wish to install it. Is it using external APIs, sending data to the server, closed source, etc.

**Comment by MidoriKami** [comment]
This is especially important and I mentioned this in https://github.com/goatcorp/DIPs/pull/28#issuecomment-1125795404

Having the ability to tag a plugin as "Modifies Native UI" would be very helpful for streamers to decide if they want to install a plugin or not.

**Comment by philpax** [comment]
Oops, didn't see this. Well, duplicated in #53.
