### ISSUE TITLE
Email notification service

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/DIPs#25]
I was doing this anyways, but maybe we can make a DIP out of [this](https://github.com/karashiiro/operator). The idea is that repositories with lots of activity to keep track of can all be reduced down to aggregated updates in emails, to lower the amount of effort that needs to be spent on filtering through everything. After the first email, all subsequent emails will only contain updates since the previous one, down to the point where there are no updates, at which point no email will be sent at all.

I can transfer this to goatcorp once it has a subscribe process implemented. I'll also write a proper DIP for this if there are no objections.

**Comment by karashiiro** [comment]
@goaaats Do you want to make an email address that can route through Outlook, or do you just want to have the credentials for [caprine.operator@outlook.com](mailto:caprine.operator@outlook.com)? Asking because I had to use my phone number to verify it, not sure if you want one with yours on it instead or if it doesn't matter.

**Comment by karashiiro** [comment]
Most other providers should be fine too, so long as they have an SMTP and IMAP server with simple/login auth.

**Comment by goaaats** [comment]
The outlook is fine, if that doesn't work, I also have SES set up for another project, should be easy to hook up
