### ISSUE TITLE
Adopt-a-plugin policy

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/DIPs#27]
We've talked about this but never formalized. Not sure if this needs a whole DIP though.

Maybe plugins that are 2 or more API levels behind and haven't been updated in 6+ months get set to "Adoptable" state. Developers can of course notify they have personal things going on and put this on pause - or look for someone to adopt earlier.

**Comment by KazWolfe** [comment]
To address an (admittedly small) elephant in the room: there has to be some way to forcefully adopt a plugin. There are absolutely edge cases that may warrant a plugin be forked and moved to a new maintainer, generally for the sake of the ecosystem or users of that plugin. Plugins *really* shouldn't be essential to player workflows (looking at XIVCombo here), but things do happen and shape up in certain ways.

I'd like to propose this DIP also cover the case of these "forced" adoptions and how they would work. The standard for such a move would likely be very high (and virtually always an exception to the rule), but should cover things like:

* Whether the new plugin is allowed to maintain the branding of the old plugin (likely not?)
* How harmful the loss of a plugin is to the ecosystem as a whole
* Ensuring the new maintainer preserves initial intent of the plugin (although this is a very nebulous concept)
* Whether the plugin would, in its forked state, even be allowed anymore on the repo.

This is more of a personal opinion of mine, but were I to leave the Dalamud community for any reason, that should *not* allow me to "poison" XIVDeck. Ideally, after some reasonable conditions have been met, someone should be able to officially take over the plugin and pick up where I left off. 

Plugins are (by necessity) licensed under AGPL, meaning forks are legally permissible and continuations are fine under the eyes of licenses. However, I feel we need to have a stance as to how these forks are handled at a user level. If someone expresses desire to adopt a plugin that's been abandoned, it should be considered.

**Comment by MidoriKami** [comment]
Also of note, it should also include the ability of a developer to declare a project as `Abandoned but not adoptable` Take Oops All Lalafels for example. While there are many that could maintain it, the concerns the original author had should be respected. At the very least, to overturn the authors request a formal discussion on why or why not a plugin should be labeled as not adoptable.

**Comment by Pilzinsel64** [comment]
I have a current case that we could use as example, if you want.
At least, it would help me with my initial question, I asked in the goat place-Discord if someone knows how to behav here.
See this and following messages:
https://discord.com/channels/581875019861328007/719513457988337724/986527296276013081

To give my five cents here... Basically I agress with almost everything what @KazWolfe and @MidoriKami explained.
What I would extend/change:
- As long, as the maintainer don't break the plugin's initial intent (extending and adding features should be able then), it should be allowed to keep the Plugin name and just change the maintainer. Maybe note in the Description or Changelog, that the maintainer has changed.
- At least 3 months of inactivity should be waited out, before a Fork can push it's own version/update to the official repo. Except the original maintaner has a official statement that someone can takeover his work. 

What do you think?

**Comment by kalilistic** [comment]
Updated verbiage from discord. If no major concerns are raised, we can consider this closed in a week. At that point, we can update the docs.

Plugins can be adopted when:
1) Consent of the current maintainer.
2) Plugin has fallen behind the current API level for at least 3 months and reasonable efforts have been made to reach the maintainer.
3) Plugin has fallen behind the current API level for at least 6 months.

Note: Maintainers can also propose to the Committee to move their plugin to a discontinued status where it is no longer eligible for adoption. The Committee will consider criteria such as the rationale and the impact on the dalamud ecosystem.

**Comment by philpax** [comment]
Done in https://github.com/goatcorp/faq/pull/83. Considered writing up a proper DIP but I think this is fine (it's not a big enough change to merit the process)
