### ISSUE TITLE
Licensing information on this repo's README

### ISSUE THREAD

**Issue by karashiiro** [goatcorp/DIPs#31]
The Contributing section has the following text:
> Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in the work by you shall be licensed as MIT without any additional terms or conditions.

This should be updated to specify that contributions will be licensed under the respective license on the target repository.

**Comment by KazWolfe** [comment]
This is already covered in part by GitHub's own [Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) as well.

> Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms. If you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede.

[Section D.6, Contributions under Repository License](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license)
